### ISSUE TITLE
White dot on workspace 1

### ISSUE THREAD

**Issue by jit-x** [marcinjahn/gnome-peek-top-bar-on-fullscreen-extension#16] opened 2024-03-13 04:27 UTC
I have a white dot on the first workspace in the top left side of my screen...

I tried turning off extensions one by one and I found that when I turn off this extension then the dot disappears

Gnome-shell version : 45.4
OS: Arch Linux x86_64 

In the image the dot is on the top left of the terminal window
![Screenshot from 2024-03-13 09-56-00](https://github.com/marcinjahn/gnome-peek-top-bar-on-fullscreen-extension/assets/162009203/2a44deac-194d-4ad7-a34d-28b2e75c6e67)

**Comment by kbdragon** [comment] 2024-03-24 19:13
Is that the reason for it??? I thought I had a burnt pixel...

**Comment by marcinjahn** [comment] 2024-03-25 19:13
Duplicate of #10

**Closed by marcinjahn** 2024-03-25 19:13 UTC
